
server:
  port: 8083
debug: false
logging :
  file:
    name: SpringBootTest.log
    path: /karun
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/testdb
     username: root
     password: root
  jpa:
     show-sql: true
     properties:
         hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect
     hibernate:
         ddl-auto: update
  mail:
    host: 
    port: 587
    username: 
    password: 
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          starttls :
            enable : true
         
      
