
server:
  port: 8083
debug: false
logging :
  file:
    name: SpringBootTest.log
    path: /karun
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/testdb
     username: postgres
     password: postgres
  jpa:
     show-sql: true
     properties:
         hibernate:
             dialect: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
         ddl-auto: update
  mail:
    host: 
    port: 587
    username: karunakar001122@gmail.com
    password: Welcome@001$
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          starttls :
            enable : true
         
      
